# Generated by Django 3.1.3 on 2020-11-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50, verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('entrada', models.TimeField(verbose_name='Hora Entrada')),
                ('almoco', models.TimeField(blank=True, null=True, verbose_name='Início do Almoço')),
                ('almoco_fim', models.TimeField(blank=True, null=True, verbose_name='Fim do Almoço')),
                ('saida', models.TimeField(verbose_name='Hora de Saída')),
                ('carro', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True, verbose_name='Carro Próprio')),
                ('zona', models.CharField(max_length=200, verbose_name='Zona')),
                ('medico', models.CharField(max_length=200, verbose_name='Médico')),
                ('servico', models.ManyToManyField(to='tracker.Servico', verbose_name='Serviço')),
            ],
        ),
    ]
