# Generated by Django 3.1.3 on 2020-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='carro',
            field=models.IntegerField(blank=True, choices=[(0, 'Unidade Móvel (NZ)'), (1, 'Unidade Móvel (SM)'), (2, 'Unidade Móvel (TP)'), (3, 'Unidade Móvel (UN)'), (4, 'Carro Próprio')], null=True, verbose_name='Carro Próprio'),
        ),
    ]
